# Generated by Django 5.2.8 on 2025-12-17 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='设置名称')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键名')),
                ('value', models.TextField(verbose_name='设置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(verbose_name='AI建议')),
                ('prompt_sent', models.TextField(blank=True, null=True, verbose_name='发送的Prompt')),
                ('conversation_context', models.TextField(blank=True, null=True, verbose_name='对话上下文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健康建议',
                'verbose_name_plural': '健康建议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(verbose_name='体检日期')),
                ('hospital', models.CharField(max_length=200, verbose_name='体检机构')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='报告文件')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '体检报告',
                'verbose_name_plural': '体检报告',
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('ocr_llm', 'MinerU Pipeline 模式 (OCR + LLM)'), ('vlm_transformers', 'MinerU VLM-Transformers 模式 (OCR + LLM)'), ('vl_model', '多模态大模型模式 (直接识别)')], default='ocr_llm', max_length=20, verbose_name='处理工作流')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('uploading', '上传中'), ('ocr_processing', 'OCR识别中'), ('ai_processing', 'AI处理中'), ('saving_data', '保存数据中'), ('completed', '处理完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('progress', models.IntegerField(default=0, verbose_name='处理进度(%)')),
                ('ocr_result', models.TextField(blank=True, null=True, verbose_name='OCR识别结果')),
                ('ai_result', models.JSONField(blank=True, null=True, verbose_name='AI处理结果')),
                ('vl_model_result', models.JSONField(blank=True, null=True, verbose_name='多模态模型处理结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='处理耗时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('health_checkup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_records.healthcheckup', verbose_name='体检报告')),
            ],
            options={
                'verbose_name': '文档处理',
                'verbose_name_plural': '文档处理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('physical_exam', '体格检查'), ('blood_routine', '血液常规'), ('biochemistry', '生化检验'), ('liver_function', '肝功能'), ('kidney_function', '肾功能'), ('thyroid_function', '甲状腺功能'), ('tumor_markers', '肿瘤标志物'), ('urine_exam', '尿液检查'), ('blood_rheology', '血液流变学'), ('eye_exam', '眼科检查'), ('ultrasound_exam', '超声检查'), ('imaging_exam', '影像学检查'), ('diagnosis', '病症诊断'), ('symptoms', '症状描述'), ('other_exam', '其他检查')], max_length=50, verbose_name='指标类型')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('value', models.CharField(max_length=100, verbose_name='检测值')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='参考范围')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('attention', '关注')], default='normal', max_length=20, verbose_name='状态')),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.healthcheckup', verbose_name='体检报告')),
            ],
            options={
                'verbose_name': '健康指标',
                'verbose_name_plural': '健康指标',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
