# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='processing_mode',
            field=models.CharField(
                max_length=20,
                choices=[('stream', '实时模式'), ('background', '后台模式')],
                default='background',
                verbose_name='AI处理模式'
            ),
        ),
    ]
