# Generated by Django 5.2.8 on 2025-12-29 13:10

from django.db import migrations


def migrate_indicator_types(apps, schema_editor):
    """迁移旧的指标类型到新的分类"""
    HealthIndicator = apps.get_model('medical_records', 'HealthIndicator')

    # 旧类型到新类型的映射
    type_mapping = {
        'physical_exam': 'general_exam',  # 体格检查 → 一般检查
        'urine_exam': 'urine',  # 尿液检查 → 尿液检查（简化名称）
        'eye_exam': 'special_organs',  # 眼科检查 → 专科检查
        'ultrasound_exam': 'ultrasound',  # 超声检查 → 超声检查（简化名称）
        'imaging_exam': 'other',  # 影像学检查 → 其他检查（需要人工审核）
        'thyroid_function': 'thyroid',  # 甲状腺功能 → 甲状腺（简化）
        'diagnosis': 'pathology',  # 病症诊断 → 病理检查（可能是病理结果）
        'symptoms': 'other',  # 症状描述 → 其他检查
        'other_exam': 'other',  # 其他检查 → 其他检查
    }

    # 更新所有指标的类型
    for old_type, new_type in type_mapping.items():
        HealthIndicator.objects.filter(indicator_type=old_type).update(indicator_type=new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_conversation_healthadvice_conversation'),
    ]

    operations = [
        migrations.RunPython(migrate_indicator_types),
    ]
