# Generated by Django 5.2.8 on 2025-12-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_update_indicator_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthindicator',
            name='indicator_type',
            field=models.CharField(choices=[('general_exam', '一般检查'), ('blood_routine', '血常规'), ('biochemistry', '生化检验'), ('liver_function', '肝功能'), ('kidney_function', '肾功能'), ('thyroid', '甲状腺'), ('cardiac', '心脏标志物'), ('tumor_markers', '肿瘤标志物'), ('infection', '感染炎症'), ('blood_rheology', '血液流变'), ('coagulation', '凝血功能'), ('urine', '尿液检查'), ('stool', '粪便检查'), ('pathology', '病理检查'), ('ultrasound', '超声检查'), ('X_ray', 'X线检查'), ('CT_MRI', 'CT和MRI'), ('endoscopy', '内镜检查'), ('special_organs', '专科检查'), ('other', '其他检查')], max_length=50, verbose_name='指标类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
