# Generated by Django 5.2.8 on 2025-12-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_add_mac_system_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthindicator',
            name='indicator_type',
            field=models.CharField(choices=[('physical_exam', '体格检查'), ('blood_routine', '血液常规'), ('biochemistry', '生化检验'), ('liver_function', '肝功能'), ('kidney_function', '肾功能'), ('thyroid_function', '甲状腺功能'), ('tumor_markers', '肿瘤标志物'), ('urine_exam', '尿液检查'), ('blood_rheology', '血液流变学'), ('eye_exam', '眼科检查'), ('ultrasound_exam', '超声检查'), ('imaging_exam', '影像学检查'), ('diagnosis', '病症诊断'), ('symptoms', '症状描述'), ('other_exam', '其他检查')], max_length=50, verbose_name='指标类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别'),
        ),
    ]
