# Generated by Django 5.2.8 on 2026-01-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_add_processing_mode'),
        ('medical_records', '0006_alter_healthindicator_indicator_type_and_more'),
    ]

    operations = [
    ]
