# Generated by Django 5.2.8 on 2026-01-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_update_legacy_indicator_types'),
        ('medical_records', '0008_add_selected_reports_to_health_advice'),
    ]

    operations = [
    ]
