# Generated by Django 5.2.8 on 2026-01-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_merge_20260119_2210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='药名')),
                ('dosage', models.CharField(max_length=100, verbose_name='服药方式')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '药单',
                'verbose_name_plural': '药单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='服药日期')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='服药时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('frequency', models.CharField(choices=[('once', '一次'), ('daily', '每日一次'), ('twice_daily', '每日两次'), ('three_times_daily', '每日三次'), ('four_times_daily', '每日四次'), ('weekly', '每周一次'), ('as_needed', '按需服用')], default='daily', max_length=20, verbose_name='服药频率')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medication', verbose_name='药单')),
            ],
            options={
                'verbose_name': '服药记录',
                'verbose_name_plural': '服药记录',
                'ordering': ['-record_date'],
                'unique_together': {('medication', 'record_date')},
            },
        ),
    ]
