# Generated by Django 6.0.2 on 2026-02-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('medical_records', '0012_add_is_generating_to_health_advice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='事件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='事件描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('event_type', models.CharField(choices=[('illness', '疾病事件'), ('checkup', '体检事件'), ('chronic_management', '慢性病管理'), ('emergency', '急诊事件'), ('wellness', '健康管理'), ('medication_course', '用药疗程'), ('other', '其他')], default='other', max_length=30, verbose_name='事件类型')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='是否自动生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健康事件',
                'verbose_name_plural': '健康事件',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('added_by', models.CharField(choices=[('auto', '自动添加'), ('manual', '手动添加')], default='manual', max_length=10, verbose_name='添加方式')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_items', to='medical_records.healthevent', verbose_name='事件')),
            ],
            options={
                'verbose_name': '事件项目',
                'verbose_name_plural': '事件项目',
                'ordering': ['event', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['user', '-start_date'], name='medical_rec_user_id_04fc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['event_type'], name='medical_rec_event_t_195a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['is_auto_generated'], name='medical_rec_is_auto_7edc10_idx'),
        ),
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['event', 'content_type', 'object_id'], name='medical_rec_event_i_c03563_idx'),
        ),
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['added_by'], name='medical_rec_added_b_d622cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventitem',
            constraint=models.UniqueConstraint(fields=('event', 'content_type', 'object_id'), name='unique_event_item'),
        ),
    ]
