# Generated by Django 6.0.2 on 2026-02-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0013_healthevent_eventitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('event_type', models.CharField(choices=[('illness', '疾病事件'), ('checkup', '体检事件'), ('chronic_management', '慢性病管理'), ('emergency', '急诊事件'), ('wellness', '健康管理'), ('medication_course', '用药疗程'), ('other', '其他')], max_length=30, verbose_name='事件类型')),
                ('suggested_duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='建议持续天数')),
                ('default_name_template', models.CharField(blank=True, max_length=200, verbose_name='默认名称模板')),
                ('is_system_template', models.BooleanField(default=False, verbose_name='系统模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '事件模板',
                'verbose_name_plural': '事件模板',
                'ordering': ['is_system_template', 'name'],
            },
        ),
    ]
