# Generated by Django 6.0.2 on 2026-02-12 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0016_userprofile_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevent',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('observing', '观察中'), ('recovered', '治愈')], default='observing', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='healthevent',
            index=models.Index(fields=['status'], name='medical_rec_status_d15588_idx'),
        ),
    ]
