# Generated by Django 4.2.28 on 2026-02-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0017_healthevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI对话总结'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ai_summary_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI总结生成时间'),
        ),
        migrations.AddField(
            model_name='healthevent',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI事件总结'),
        ),
        migrations.AddField(
            model_name='healthevent',
            name='ai_summary_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI总结生成时间'),
        ),
        migrations.CreateModel(
            name='MedicationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='药单组名称')),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='medication_images/%Y/%m/', verbose_name='来源图片')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='AI总结')),
                ('raw_result', models.JSONField(blank=True, null=True, verbose_name='原始识别结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '药单组',
                'verbose_name_plural': '药单组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='medical_records.medicationgroup', verbose_name='所属药单组'),
        ),
    ]
