# Generated by Django 4.2.28 on 2026-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0018_conversation_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckup',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI解读总结'),
        ),
        migrations.AddField(
            model_name='healthcheckup',
            name='ai_summary_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI总结生成时间'),
        ),
    ]
