# Generated by Django 5.2.8 on 2026-02-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0019_healthcheckup_ai_summary_and_more'),
        ('medical_records', '0019_healthevent_ai_summary_and_more'),
    ]

    operations = [
    ]
