# Generated by Django 4.2.28 on 2026-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0019_healthcheckup_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthadvice',
            name='selected_event',
            field=models.IntegerField(blank=True, null=True, verbose_name='选中的健康事件ID'),
        ),
    ]
