# Generated by Django 5.2.8 on 2026-02-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0020_healthadvice_selected_event'),
        ('medical_records', '0020_merge_20260216_1542'),
    ]

    operations = [
    ]
