# Generated by Django 4.2.28 on 2026-02-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0021_merge_20260216_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_custom_username',
            field=models.BooleanField(default=False, verbose_name='是否已设置自定义账号'),
        ),
    ]
