# Generated by Django 4.2.28 on 2026-02-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0022_userprofile_has_custom_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDocumentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='批次名称')),
                ('checkup_date', models.DateField(verbose_name='体检日期')),
                ('hospital', models.CharField(default='未知机构', max_length=200, verbose_name='体检机构')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '处理完成'), ('failed', '处理失败'), ('partial_failed', '部分失败')], default='pending', max_length=20, verbose_name='批次状态')),
                ('total_files', models.IntegerField(default=0, verbose_name='文件总数')),
                ('completed_files', models.IntegerField(default=0, verbose_name='已完成文件数')),
                ('failed_files', models.IntegerField(default=0, verbose_name='失败文件数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '批量文档处理',
                'verbose_name_plural': '批量文档处理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchProcessingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', '图片')], max_length=10, verbose_name='文件类型')),
                ('workflow_type', models.CharField(max_length=20, verbose_name='工作流类型')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('uploading', '上传中'), ('ocr_processing', 'OCR识别中'), ('ai_processing', 'AI处理中'), ('saving_data', '保存数据中'), ('completed', '处理完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('progress', models.IntegerField(default=0, verbose_name='处理进度(%)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.batchdocumentprocessing', verbose_name='批量任务')),
                ('document_processing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.documentprocessing', verbose_name='文档处理')),
                ('health_checkup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.healthcheckup', verbose_name='体检报告')),
            ],
            options={
                'verbose_name': '批量处理项',
                'verbose_name_plural': '批量处理项',
                'ordering': ['created_at'],
            },
        ),
    ]
